mysql:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: its_a_secret_to_everybody
    MYSQL_USER: subversion
    MYSQL_PASSWORD: subversion
    MYSQL_DATABASE: subversion
  ports:
    - "3306"
blog:
  build: .
  links:
    - mysql
  ports:
    - "8888:8888"
